teamName: team-a
appName: showcase
repoUrl: https://github.com/suxess-it/team-a-showcase
createAppNamespace: true
stages:
  - name: "test"
    subscriptions: 
      warehouse: "warehouse-{{ .Values.appName }}"
  - name: "qa"
    subscriptions: 
      upstreamStages:
      - name: test
  - name: "prod"
    subscriptions: 
      upstreamStages:
      - name: qa